- name: Install additional packets
  apt:
    name:
      - curl
      - ca-certificates
      - python3-psycopg2
      - libpq-dev
      - python3-pip
      - acl
    state: present
    update_cache: yes

- name: Install psycopg2
  pip:
    name: psycopg2-binary
    executable: pip3

- name: Create directory for PostgreSQL repository keys
  file:
    path: /usr/share/postgresql-common/pgdg
    state: directory
    mode: '0755'

- name: Download PostgreSQL repository key
  get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    mode: '0644'

- name: Add PostgreSQL APT repository
  apt_repository:
    repo: >
      deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc]
      https://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install PostgreSQL and required packages
  apt:
    name:
      - postgresql

- name: Ensure PostgreSQL is started and enabled
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Create a new database with name "test"
  become_user: postgres
  community.postgresql.postgresql_db:
    name: test

- name: Create table peers
  become_user: postgres
  community.postgresql.postgresql_query:
    db: test
    query: |
      CREATE TABLE IF NOT EXISTS peers (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL
      );

- name: Insert values in table peers
  become_user: postgres
  community.postgresql.postgresql_query:
    db: test
    query: |
      INSERT INTO peers (name)
      VALUES ('grapefru1'), ('grapefru'), ('grapefru');