---
- name: Update packets
  apt:
    update_cache: yes

- name: Install apache service
  apt:
    name: apache2

- name: Start apache service
  service:
    name: apache2
    state: started
    enabled: yes